"""competitor_features

Revision ID: 1cbc05e8f2b4
Revises: add_vendors_table
Create Date: 2026-02-06 21:32:01.770326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cbc05e8f2b4'
down_revision: Union[str, Sequence[str], None] = 'add_vendors_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classification_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('realm_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('priority', sa.Numeric(), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('action', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['realm_id'], ['qbo_connections.realm_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classification_rules_realm_id'), 'classification_rules', ['realm_id'], unique=False)
    op.create_table('vendor_aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('realm_id', sa.String(), nullable=True),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['realm_id'], ['qbo_connections.realm_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_aliases_realm_id'), 'vendor_aliases', ['realm_id'], unique=False)
    op.add_column('bank_accounts', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('bank_accounts', sa.Column('is_connected', sa.Boolean(), nullable=True))
    op.add_column('transactions', sa.Column('potential_duplicate_id', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('duplicate_confidence', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('transactions', sa.Column('is_excluded', sa.Boolean(), nullable=True))
    op.add_column('transactions', sa.Column('forced_review', sa.Boolean(), nullable=True))
    op.add_column('transactions', sa.Column('sync_token', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('suggested_payee', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('category_id', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('category_name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'transactions', ['potential_duplicate_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'category_name')
    op.drop_column('transactions', 'category_id')
    op.drop_column('transactions', 'suggested_payee')
    op.drop_column('transactions', 'sync_token')
    op.drop_column('transactions', 'forced_review')
    op.drop_column('transactions', 'is_excluded')
    op.drop_column('transactions', 'duplicate_confidence')
    op.drop_column('transactions', 'potential_duplicate_id')
    op.drop_column('bank_accounts', 'is_connected')
    op.drop_column('bank_accounts', 'is_active')
    op.drop_index(op.f('ix_vendor_aliases_realm_id'), table_name='vendor_aliases')
    op.drop_table('vendor_aliases')
    op.drop_index(op.f('ix_classification_rules_realm_id'), table_name='classification_rules')
    op.drop_table('classification_rules')
    # ### end Alembic commands ###
