"""add structured reasoning fields to transactions

Revision ID: 2ead4a30aa71
Revises: 5f44511828bf
Create Date: 2026-02-01 01:11:50.175264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ead4a30aa71'
down_revision: Union[str, Sequence[str], None] = '5f44511828bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('vendor_reasoning', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('category_reasoning', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('note_reasoning', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('tax_deduction_note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'tax_deduction_note')
    op.drop_column('transactions', 'note_reasoning')
    op.drop_column('transactions', 'category_reasoning')
    op.drop_column('transactions', 'vendor_reasoning')
    # ### end Alembic commands ###
