"""Add token system to user model

Revision ID: 3188f586677c
Revises: f95351d0ab19
Create Date: 2026-01-26 11:49:49.386919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3188f586677c'
down_revision: Union[str, Sequence[str], None] = 'f95351d0ab19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_analytics_events_event_name'), table_name='analytics_events')
    # op.drop_index(op.f('ix_analytics_events_user_id'), table_name='analytics_events')
    # op.drop_table('analytics_events')
    op.add_column('transactions', sa.Column('is_split', sa.JSON(), nullable=True))
    op.add_column('transactions', sa.Column('receipt_url', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('receipt_data', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('token_balance', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('monthly_token_allowance', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_refill_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_refill_date')
    op.drop_column('users', 'monthly_token_allowance')
    op.drop_column('users', 'token_balance')
    op.drop_column('transactions', 'receipt_data')
    op.drop_column('transactions', 'receipt_url')
    op.drop_column('transactions', 'is_split')
    op.create_table('analytics_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('properties', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('analytics_events_pkey'))
    )
    op.create_index(op.f('ix_analytics_events_user_id'), 'analytics_events', ['user_id'], unique=False)
    op.create_index(op.f('ix_analytics_events_event_name'), 'analytics_events', ['event_name'], unique=False)
    # ### end Alembic commands ###
