"""Add persistent memory models

Revision ID: 3edfac8da539
Revises: 1bf5d2a3e4a8
Create Date: 2026-02-15 00:45:17.783697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3edfac8da539'
down_revision: Union[str, Sequence[str], None] = '1bf5d2a3e4a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorization_learning',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('vendor_name', sa.String(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.Column('matching_method', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorization_learning_user_id'), 'categorization_learning', ['user_id'], unique=False)
    op.create_index(op.f('ix_categorization_learning_vendor_name'), 'categorization_learning', ['vendor_name'], unique=False)
    op.create_table('transaction_persistence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('qbo_id', sa.String(), nullable=False),
    sa.Column('realm_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.Column('payee', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_persistence_qbo_id'), 'transaction_persistence', ['qbo_id'], unique=False)
    op.create_index(op.f('ix_transaction_persistence_realm_id'), 'transaction_persistence', ['realm_id'], unique=False)
    op.create_index(op.f('ix_transaction_persistence_user_id'), 'transaction_persistence', ['user_id'], unique=False)
    op.add_column('transactions', sa.Column('matching_method', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'matching_method')
    op.drop_index(op.f('ix_transaction_persistence_user_id'), table_name='transaction_persistence')
    op.drop_index(op.f('ix_transaction_persistence_realm_id'), table_name='transaction_persistence')
    op.drop_index(op.f('ix_transaction_persistence_qbo_id'), table_name='transaction_persistence')
    op.drop_table('transaction_persistence')
    op.drop_index(op.f('ix_categorization_learning_vendor_name'), table_name='categorization_learning')
    op.drop_index(op.f('ix_categorization_learning_user_id'), table_name='categorization_learning')
    op.drop_table('categorization_learning')
    # ### end Alembic commands ###
